### push
POST {{base_url}}/api/github/{{group_id}}
Content-Type: application/json
Accept: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/42",
    "before": "affda8e6c1246c8d77b6f7723bb46aeca64dd394",
    "after": "0000000000000000000000000000000000000000",
    "repository": {
        "id": 711464286,
        "node_id": "R_kgDOKmgVXg",
        "name": "upl-sms",
        "full_name": "MarienMupenda/upl-sms",
        "private": true,
        "owner": {
            "name": "MarienMupenda",
            "email": "57844897+MarienMupenda@users.noreply.github.com",
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/MarienMupenda/upl-sms",
        "description": null,
        "fork": false,
        "url": "https://github.com/MarienMupenda/upl-sms",
        "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
        "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
        "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
        "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
        "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
        "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
        "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
        "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
        "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
        "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
        "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
        "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
        "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
        "created_at": 1698576939,
        "updated_at": "2023-11-05T19:30:16Z",
        "pushed_at": 1699305309,
        "git_url": "git://github.com/MarienMupenda/upl-sms.git",
        "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
        "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
        "svn_url": "https://github.com/MarienMupenda/upl-sms",
        "homepage": null,
        "size": 25354,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 22,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 22,
        "watchers": 0,
        "default_branch": "master",
        "stargazers": 0,
        "master_branch": "master"
    },
    "pusher": {
        "name": "MarienMupenda",
        "email": "57844897+MarienMupenda@users.noreply.github.com"
    },
    "sender": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    },
    "created": false,
    "deleted": false,
    "forced": false,
    "base_ref": null,
    "compare": "https://github.com/MarienMupenda/upl-sms/compare/affda8e6c124...000000000000",
    "commits": [
    ],
    "head_commit": {
        "id": "3001e3b1e0f0f675708edd00b1f9f1a5c2f8436f",
        "tree_id": "c45de083883fab9571953ce8cd5b14b7c2624a69",
        "distinct": true,
        "message": "Merge pull request #157 from MarienMupenda/156\n\n156 : [Finance]  Gérer FraisCategorie",
        "timestamp": "2023-11-23T10:34:38+02:00",
        "url": "https://github.com/MarienMupenda/upl-sms/commit/3001e3b1e0f0f675708edd00b1f9f1a5c2f8436f",
        "author": {
            "name": "Marien Mupenda",
            "email": "57844897+MarienMupenda@users.noreply.github.com",
            "username": "MarienMupenda"
        },
        "committer": {
            "name": "GitHub",
            "email": "noreply@github.com",
            "username": "web-flow"
        },
        "added": [
            "finance/app/Http/Livewire/FraisCategories/CreateUpdateFraisCategorie.php",
            "finance/app/Http/Livewire/FraisCategories/ListFraisCategories.php",
            "finance/app/Http/Livewire/Users/ListUsersComponent.php",
            "finance/resources/views/livewire/frais_categories/create_update-frais_categorie.blade.php",
            "finance/resources/views/livewire/frais_categories/list-frais_categories.blade.php",
            "finance/tests/Feature/Pages/FraisCategoriesTest.php"
        ],
        "removed": [
            "finance/app/Http/Livewire/Users/ListUsers.php"
        ],
        "modified": [
            "finance/resources/views/partials/sidebar.blade.php",
            "finance/routes/web.php",
            "finance/tests/Feature/Pages/FraisTest.php"
        ]
    }
}


### issue
POST {{base_url}}/api/github/{{group_id}}
Content-Type: application/json
Accept: application/json
X-GitHub-Event: issues

{
    "action": "closed",
    "issue": {
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/66",
        "repository_url": "https://api.github.com/repos/MarienMupenda/upl-sms",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/66/labels{/name}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/66/comments",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/66/events",
        "html_url": "https://github.com/MarienMupenda/upl-sms/issues/66",
        "id": 1985085454,
        "node_id": "I_kwDOKmgVXs52UgAO",
        "number": 66,
        "title": "[api] consulter les promotions",
        "user": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "MarienMupenda",
                "id": 57844897,
                "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/MarienMupenda",
                "html_url": "https://github.com/MarienMupenda",
                "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2023-11-09T08:28:35Z",
        "updated_at": "2023-11-09T08:28:35Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
            "url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/66/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/66/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    "repository": {
        "id": 711464286,
        "node_id": "R_kgDOKmgVXg",
        "name": "upl-sms",
        "full_name": "MarienMupenda/upl-sms",
        "private": true,
        "owner": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/MarienMupenda/upl-sms",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms",
        "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
        "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
        "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
        "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
        "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
        "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
        "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
        "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
        "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
        "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
        "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
        "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
        "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
        "created_at": "2023-10-29T10:55:39Z",
        "updated_at": "2023-11-05T19:30:16Z",
        "pushed_at": "2023-11-09T08:27:26Z",
        "git_url": "git://github.com/MarienMupenda/upl-sms.git",
        "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
        "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
        "svn_url": "https://github.com/MarienMupenda/upl-sms",
        "homepage": null,
        "size": 25873,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 20,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 20,
        "watchers": 0,
        "default_branch": "master"
    },
    "sender": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    }
}

### milestone
POST {{base_url}}/api/github/{{group_id}}
Content-Type: application/json
Accept: application/json
X-GitHub-Event: milestone

{
    "action": "closed",
    "milestone": {
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones/8",
        "html_url": "https://github.com/MarienMupenda/upl-sms/milestone/8",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones/8/labels",
        "id": 10134643,
        "node_id": "MI_kwDOKmgVXs4AmqRz",
        "number": 8,
        "title": "Conception de l'architecure et initialization du projet",
        "description": "",
        "creator": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 0,
        "closed_issues": 17,
        "state": "closed",
        "created_at": "2023-11-02T07:05:44Z",
        "updated_at": "2023-11-10T07:37:41Z",
        "due_on": "2023-11-05T07:00:00Z",
        "closed_at": "2023-11-10T07:37:41Z"
    },
    "repository": {
        "id": 711464286,
        "node_id": "R_kgDOKmgVXg",
        "name": "upl-sms",
        "full_name": "MarienMupenda/upl-sms",
        "private": true,
        "owner": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/MarienMupenda/upl-sms",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms",
        "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
        "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
        "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
        "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
        "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
        "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
        "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
        "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
        "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
        "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
        "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
        "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
        "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
        "created_at": "2023-10-29T10:55:39Z",
        "updated_at": "2023-11-05T19:30:16Z",
        "pushed_at": "2023-11-10T07:35:14Z",
        "git_url": "git://github.com/MarienMupenda/upl-sms.git",
        "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
        "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
        "svn_url": "https://github.com/MarienMupenda/upl-sms",
        "homepage": null,
        "size": 25595,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 19,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 19,
        "watchers": 0,
        "default_branch": "master"
    },
    "sender": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    }
}


### PR Closed
POST {{base_url}}/api/github/{{group_id}}
Content-Type: application/json
Accept: application/json
X-GitHub-Event: pull_request

{
    "action": "closed",
    "number": 155,
    "pull_request": {
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/155",
        "id": 1613595009,
        "node_id": "PR_kwDOKmgVXs5gLYGB",
        "html_url": "https://github.com/MarienMupenda/upl-sms/pull/155",
        "diff_url": "https://github.com/MarienMupenda/upl-sms/pull/155.diff",
        "patch_url": "https://github.com/MarienMupenda/upl-sms/pull/155.patch",
        "issue_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/155",
        "number": 155,
        "state": "closed",
        "locked": false,
        "title": "152 : [Finance]  Gerer les frais",
        "user": {
            "login": "francisnnumbi",
            "id": 23620828,
            "node_id": "MDQ6VXNlcjIzNjIwODI4",
            "avatar_url": "https://avatars.githubusercontent.com/u/23620828?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/francisnnumbi",
            "html_url": "https://github.com/francisnnumbi",
            "followers_url": "https://api.github.com/users/francisnnumbi/followers",
            "following_url": "https://api.github.com/users/francisnnumbi/following{/other_user}",
            "gists_url": "https://api.github.com/users/francisnnumbi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/francisnnumbi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/francisnnumbi/subscriptions",
            "organizations_url": "https://api.github.com/users/francisnnumbi/orgs",
            "repos_url": "https://api.github.com/users/francisnnumbi/repos",
            "events_url": "https://api.github.com/users/francisnnumbi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/francisnnumbi/received_events",
            "type": "User",
            "site_admin": false
        },
        "body": null,
        "created_at": "2023-11-22T22:43:20Z",
        "updated_at": "2023-11-23T06:57:22Z",
        "closed_at": "2023-11-23T06:57:22Z",
        "merged_at": "2023-11-23T06:57:22Z",
        "merge_commit_sha": "a0f6ca84c4ab86a28ea6308e7a3e01da97aed7ea",
        "assignee": null,
        "assignees": [
        ],
        "requested_reviewers": [
        ],
        "requested_teams": [
        ],
        "labels": [
        ],
        "milestone": {
            "url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones/3",
            "html_url": "https://github.com/MarienMupenda/upl-sms/milestone/3",
            "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones/3/labels",
            "id": 10119564,
            "node_id": "MI_kwDOKmgVXs4AmmmM",
            "number": 3,
            "title": "Perception financiere ",
            "description": "1. Gestion des frais.\r\n2. Perception des frais.\r\n3. Liste des perceptions. \r\n4. Endpoint pour affichages de etudiants ayants payes.\r\n4. Gestions de roles, permissions et utilisateurs.\r\n5. Creation du projet.",
            "creator": {
                "login": "MarienMupenda",
                "id": 57844897,
                "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/MarienMupenda",
                "html_url": "https://github.com/MarienMupenda",
                "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 2,
            "closed_issues": 7,
            "state": "open",
            "created_at": "2023-10-29T21:49:30Z",
            "updated_at": "2023-11-23T06:57:22Z",
            "due_on": "2023-11-30T08:00:00Z",
            "closed_at": null
        },
        "draft": false,
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/155/commits",
        "review_comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/155/comments",
        "review_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/155/comments",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/73533ab4a107c81e5a860ae7785fa1c4b57ec436",
        "head": {
            "label": "MarienMupenda:152",
            "ref": "152",
            "sha": "73533ab4a107c81e5a860ae7785fa1c4b57ec436",
            "user": {
                "login": "MarienMupenda",
                "id": 57844897,
                "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/MarienMupenda",
                "html_url": "https://github.com/MarienMupenda",
                "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                "type": "User",
                "site_admin": false
            },
            "repo": {
                "id": 711464286,
                "node_id": "R_kgDOKmgVXg",
                "name": "upl-sms",
                "full_name": "MarienMupenda/upl-sms",
                "private": true,
                "owner": {
                    "login": "MarienMupenda",
                    "id": 57844897,
                    "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                    "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/MarienMupenda",
                    "html_url": "https://github.com/MarienMupenda",
                    "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                    "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                    "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                    "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                    "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                    "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "html_url": "https://github.com/MarienMupenda/upl-sms",
                "description": null,
                "fork": false,
                "url": "https://api.github.com/repos/MarienMupenda/upl-sms",
                "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
                "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
                "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
                "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
                "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
                "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
                "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
                "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
                "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
                "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
                "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
                "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
                "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
                "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
                "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
                "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
                "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
                "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
                "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
                "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
                "created_at": "2023-10-29T10:55:39Z",
                "updated_at": "2023-11-05T19:30:16Z",
                "pushed_at": "2023-11-23T06:57:22Z",
                "git_url": "git://github.com/MarienMupenda/upl-sms.git",
                "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
                "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
                "svn_url": "https://github.com/MarienMupenda/upl-sms",
                "homepage": null,
                "size": 26437,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "JavaScript",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": true,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 9,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [
                ],
                "visibility": "private",
                "forks": 0,
                "open_issues": 9,
                "watchers": 0,
                "default_branch": "main",
                "allow_squash_merge": true,
                "allow_merge_commit": true,
                "allow_rebase_merge": true,
                "allow_auto_merge": true,
                "delete_branch_on_merge": true,
                "allow_update_branch": false,
                "use_squash_pr_title_as_default": false,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "PR_TITLE",
                "merge_commit_title": "MERGE_MESSAGE"
            }
        },
        "base": {
            "label": "MarienMupenda:main",
            "ref": "main",
            "sha": "1892c2a887b7297fa93aebfd441f5fdd9eb28c1a",
            "user": {
                "login": "MarienMupenda",
                "id": 57844897,
                "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/MarienMupenda",
                "html_url": "https://github.com/MarienMupenda",
                "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                "type": "User",
                "site_admin": false
            },
            "repo": {
                "id": 711464286,
                "node_id": "R_kgDOKmgVXg",
                "name": "upl-sms",
                "full_name": "MarienMupenda/upl-sms",
                "private": true,
                "owner": {
                    "login": "MarienMupenda",
                    "id": 57844897,
                    "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                    "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/MarienMupenda",
                    "html_url": "https://github.com/MarienMupenda",
                    "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                    "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                    "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                    "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                    "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                    "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "html_url": "https://github.com/MarienMupenda/upl-sms",
                "description": null,
                "fork": false,
                "url": "https://api.github.com/repos/MarienMupenda/upl-sms",
                "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
                "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
                "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
                "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
                "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
                "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
                "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
                "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
                "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
                "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
                "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
                "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
                "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
                "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
                "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
                "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
                "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
                "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
                "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
                "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
                "created_at": "2023-10-29T10:55:39Z",
                "updated_at": "2023-11-05T19:30:16Z",
                "pushed_at": "2023-11-23T06:57:22Z",
                "git_url": "git://github.com/MarienMupenda/upl-sms.git",
                "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
                "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
                "svn_url": "https://github.com/MarienMupenda/upl-sms",
                "homepage": null,
                "size": 26437,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "JavaScript",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": true,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 9,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [
                ],
                "visibility": "private",
                "forks": 0,
                "open_issues": 9,
                "watchers": 0,
                "default_branch": "main",
                "allow_squash_merge": true,
                "allow_merge_commit": true,
                "allow_rebase_merge": true,
                "allow_auto_merge": true,
                "delete_branch_on_merge": true,
                "allow_update_branch": false,
                "use_squash_pr_title_as_default": false,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "PR_TITLE",
                "merge_commit_title": "MERGE_MESSAGE"
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/155"
            },
            "html": {
                "href": "https://github.com/MarienMupenda/upl-sms/pull/155"
            },
            "issue": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/155"
            },
            "comments": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/155/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/155/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls/155/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/73533ab4a107c81e5a860ae7785fa1c4b57ec436"
            }
        },
        "author_association": "COLLABORATOR",
        "auto_merge": null,
        "active_lock_reason": null,
        "merged": true,
        "mergeable": null,
        "rebaseable": null,
        "mergeable_state": "unknown",
        "merged_by": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "comments": 0,
        "review_comments": 0,
        "maintainer_can_modify": false,
        "commits": 4,
        "additions": 307,
        "deletions": 8,
        "changed_files": 10
    },
    "repository": {
        "id": 711464286,
        "node_id": "R_kgDOKmgVXg",
        "name": "upl-sms",
        "full_name": "MarienMupenda/upl-sms",
        "private": true,
        "owner": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/MarienMupenda/upl-sms",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms",
        "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
        "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
        "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
        "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
        "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
        "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
        "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
        "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
        "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
        "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
        "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
        "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
        "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
        "created_at": "2023-10-29T10:55:39Z",
        "updated_at": "2023-11-05T19:30:16Z",
        "pushed_at": "2023-11-23T06:57:22Z",
        "git_url": "git://github.com/MarienMupenda/upl-sms.git",
        "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
        "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
        "svn_url": "https://github.com/MarienMupenda/upl-sms",
        "homepage": null,
        "size": 26437,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 9,
        "watchers": 0,
        "default_branch": "main"
    },
    "sender": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    }
}
