### push
POST {{base_url}}/api/github/{{group_id}}
Content-Type: application/json
Accept: application/json
X-GitHub-Event: push

{
    "ref": "refs/heads/42",
    "before": "affda8e6c1246c8d77b6f7723bb46aeca64dd394",
    "after": "0000000000000000000000000000000000000000",
    "repository": {
        "id": 711464286,
        "node_id": "R_kgDOKmgVXg",
        "name": "upl-sms",
        "full_name": "MarienMupenda/upl-sms",
        "private": true,
        "owner": {
            "name": "MarienMupenda",
            "email": "57844897+MarienMupenda@users.noreply.github.com",
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/MarienMupenda/upl-sms",
        "description": null,
        "fork": false,
        "url": "https://github.com/MarienMupenda/upl-sms",
        "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
        "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
        "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
        "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
        "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
        "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
        "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
        "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
        "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
        "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
        "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
        "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
        "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
        "created_at": 1698576939,
        "updated_at": "2023-11-05T19:30:16Z",
        "pushed_at": 1699305309,
        "git_url": "git://github.com/MarienMupenda/upl-sms.git",
        "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
        "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
        "svn_url": "https://github.com/MarienMupenda/upl-sms",
        "homepage": null,
        "size": 25354,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 22,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 22,
        "watchers": 0,
        "default_branch": "master",
        "stargazers": 0,
        "master_branch": "master"
    },
    "pusher": {
        "name": "MarienMupenda",
        "email": "57844897+MarienMupenda@users.noreply.github.com"
    },
    "sender": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    },
    "created": false,
    "deleted": true,
    "forced": false,
    "base_ref": null,
    "compare": "https://github.com/MarienMupenda/upl-sms/compare/affda8e6c124...000000000000",
    "commits": [
    ],
    "head_commit": null
}


### issue
POST {{base_url}}/api/github/{{group_id}}
Content-Type: application/json
Accept: application/json
X-GitHub-Event: issues

{
    "action": "assigned",
    "issue": {
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/62",
        "repository_url": "https://api.github.com/repos/MarienMupenda/upl-sms",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/62/labels{/name}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/62/comments",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/62/events",
        "html_url": "https://github.com/MarienMupenda/upl-sms/issues/62",
        "id": 1984414609,
        "node_id": "I_kwDOKmgVXs52R8OR",
        "number": 62,
        "title": "[faculte] associer enseingant promotion ecours et annee",
        "user": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [
            {
                "login": "MarienMupenda",
                "id": 57844897,
                "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/MarienMupenda",
                "html_url": "https://github.com/MarienMupenda",
                "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": {
            "url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones/2",
            "html_url": "https://github.com/MarienMupenda/upl-sms/milestone/2",
            "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones/2/labels",
            "id": 10119562,
            "node_id": "MI_kwDOKmgVXs4AmmmK",
            "number": 2,
            "title": "Programmation des horaires et publication",
            "description": "",
            "creator": {
                "login": "MarienMupenda",
                "id": 57844897,
                "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
                "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/MarienMupenda",
                "html_url": "https://github.com/MarienMupenda",
                "followers_url": "https://api.github.com/users/MarienMupenda/followers",
                "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
                "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
                "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
                "repos_url": "https://api.github.com/users/MarienMupenda/repos",
                "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
                "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 15,
            "closed_issues": 5,
            "state": "open",
            "created_at": "2023-10-29T21:48:28Z",
            "updated_at": "2023-11-09T08:29:37Z",
            "due_on": "2023-11-18T08:00:00Z",
            "closed_at": null
        },
        "comments": 0,
        "created_at": "2023-11-08T21:18:28Z",
        "updated_at": "2023-11-09T20:37:00Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
            "url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/62/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/62/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    "assignee": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    },
    "repository": {
        "id": 711464286,
        "node_id": "R_kgDOKmgVXg",
        "name": "upl-sms",
        "full_name": "MarienMupenda/upl-sms",
        "private": true,
        "owner": {
            "login": "MarienMupenda",
            "id": 57844897,
            "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarienMupenda",
            "html_url": "https://github.com/MarienMupenda",
            "followers_url": "https://api.github.com/users/MarienMupenda/followers",
            "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
            "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
            "repos_url": "https://api.github.com/users/MarienMupenda/repos",
            "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/MarienMupenda/upl-sms",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/MarienMupenda/upl-sms",
        "forks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/forks",
        "keys_url": "https://api.github.com/repos/MarienMupenda/upl-sms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/MarienMupenda/upl-sms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/MarienMupenda/upl-sms/teams",
        "hooks_url": "https://api.github.com/repos/MarienMupenda/upl-sms/hooks",
        "issue_events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/MarienMupenda/upl-sms/events",
        "assignees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/MarienMupenda/upl-sms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/tags",
        "blobs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/MarienMupenda/upl-sms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/MarienMupenda/upl-sms/languages",
        "stargazers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/stargazers",
        "contributors_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contributors",
        "subscribers_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscribers",
        "subscription_url": "https://api.github.com/repos/MarienMupenda/upl-sms/subscription",
        "commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/MarienMupenda/upl-sms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/MarienMupenda/upl-sms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/MarienMupenda/upl-sms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/MarienMupenda/upl-sms/merges",
        "archive_url": "https://api.github.com/repos/MarienMupenda/upl-sms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/MarienMupenda/upl-sms/downloads",
        "issues_url": "https://api.github.com/repos/MarienMupenda/upl-sms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/MarienMupenda/upl-sms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/MarienMupenda/upl-sms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/MarienMupenda/upl-sms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/MarienMupenda/upl-sms/labels{/name}",
        "releases_url": "https://api.github.com/repos/MarienMupenda/upl-sms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/MarienMupenda/upl-sms/deployments",
        "created_at": "2023-10-29T10:55:39Z",
        "updated_at": "2023-11-05T19:30:16Z",
        "pushed_at": "2023-11-09T19:35:11Z",
        "git_url": "git://github.com/MarienMupenda/upl-sms.git",
        "ssh_url": "git@github.com:MarienMupenda/upl-sms.git",
        "clone_url": "https://github.com/MarienMupenda/upl-sms.git",
        "svn_url": "https://github.com/MarienMupenda/upl-sms",
        "homepage": null,
        "size": 25572,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 17,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 17,
        "watchers": 0,
        "default_branch": "master"
    },
    "sender": {
        "login": "MarienMupenda",
        "id": 57844897,
        "node_id": "MDQ6VXNlcjU3ODQ0ODk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/57844897?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarienMupenda",
        "html_url": "https://github.com/MarienMupenda",
        "followers_url": "https://api.github.com/users/MarienMupenda/followers",
        "following_url": "https://api.github.com/users/MarienMupenda/following{/other_user}",
        "gists_url": "https://api.github.com/users/MarienMupenda/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MarienMupenda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MarienMupenda/subscriptions",
        "organizations_url": "https://api.github.com/users/MarienMupenda/orgs",
        "repos_url": "https://api.github.com/users/MarienMupenda/repos",
        "events_url": "https://api.github.com/users/MarienMupenda/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MarienMupenda/received_events",
        "type": "User",
        "site_admin": false
    }
}
